### ISSUE TITLE
CP4 pretrain：missing the npy file

### ISSUE THREAD

**Issue by Viki520** [CinqueOrigin/NG-Midiformer#2]
In midi-preprocess, when running to the CP4 pre-training phase:python npy2cp4Unicode.py --input_path dataSet/PianoDataset/cp4 --output_path dataSet/PianoDataset/cp4/mergedpretrain.txt --CP_dict ~/MIDI-BERT/data_creation/prepare_data/dict/CP.pkl --mode pretrain
Traceback (most recent call last):
  File "npy2cp4Unicode.py", line 250, in <module>
    npy2cp4Unicode_txt(args.input_path,args.mode,args.output_path,
  File "npy2cp4Unicode.py", line 82, in npy2cp4Unicode_txt
    res = np.empty((0,data[0].shape[1],data[0].shape[2]),dtype=np.int64)
IndexError: list index out of range
Pls where did the npy file in this step come from？There were no previous steps on CP4 either.Can someone help me？

**Comment by CinqueOrigin** [comment]
Thank you very much for your interest in our paper! 
The error in the code you encountered at “--input_path dataSet/PianoDataset/cp4” actually refers to some npy files, which we forgot to mention in the readme file. In fact, examples of these files can be found at https://github.com/wazenmai/MIDI-BERT/tree/CP/Data/CP_data, and the way these files are generated can be referenced in the third step of the following file: https://github.com/wazenmai/MIDI-BERT/tree/CP/data_creation.

Wish you smooth progress in your work and a happy life!

**Comment by ElunaMamka** [comment]
> In midi-preprocess, when running to the CP4 pre-training phase:python npy2cp4Unicode.py --input_path dataSet/PianoDataset/cp4 --output_path dataSet/PianoDataset/cp4/mergedpretrain.txt --CP_dict ~/MIDI-BERT/data_creation/prepare_data/dict/CP.pkl --mode pretrain Traceback (most recent call last): File "npy2cp4Unicode.py", line 250, in npy2cp4Unicode_txt(args.input_path,args.mode,args.output_path, File "npy2cp4Unicode.py", line 82, in npy2cp4Unicode_txt res = np.empty((0,data[0].shape[1],data[0].shape[2]),dtype=np.int64) IndexError: list index out of range Pls where did the npy file in this step come from？There were no previous steps on CP4 either.Can someone help me？

Thank you very much for your interest in our paper!
The error in the code you encountered at “--input_path dataSet/PianoDataset/cp4” actually refers to some npy files, which we forgot to mention in the readme file. In fact, examples of these files can be found at https://github.com/wazenmai/MIDI-BERT/tree/CP/Data/CP_data, and the way these files are generated can be referenced in the third step of the following file: https://github.com/wazenmai/MIDI-BERT/tree/CP/data_creation.

Wish you smooth progress in your work and a happy life!
